# Generated by Django 4.2 on 2023-05-01 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('name', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('street', models.CharField(max_length=200)),
                ('number', models.IntegerField()),
                ('postal_code', models.IntegerField()),
                ('locality', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('auto_increment_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date', models.DateTimeField()),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.place')),
            ],
        ),
    ]
